ALTER TABLE vi_run_queue_items ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE vi_run_queue_items ADD COLUMN IF NOT EXISTS fail_policy TEXT NOT NULL DEFAULT 'stop';
ALTER TABLE vi_run_queue_items ADD COLUMN IF NOT EXISTS limits_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE vi_run_queue_items ADD COLUMN IF NOT EXISTS note TEXT NOT NULL DEFAULT '';
